---
# Installs apt and python packages

- name: Install Apt packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 3600
  become: true
  with_flattened:
    - python-numpy # Compute averages for user interface (talk about overkill)
    - python-pip # install later packages
    - python-smbus # i2c
    - python-dev # required to build later pip packages
    - libi2c-dev # i2c
    - i2c-tools # i2c
    - git # Clone babel, clone lcd library 
    - gcc # Build babel
    - vim # I need mah syntax highlighting
    - netcat # traffic generator
    - tcpdump

# This does not need become, raspbian handles user packages for python
# differently from fedora/ubuntu etc this causes problems with the pip module
- name: Install Python Packages
  shell: "sudo pip install {{item}}"
  with_items:
    - git+https://github.com/adafruit/Adafruit_Python_CharLCD.git#egg=Adafruit_CharLCD
    - RPi.GPIO
    - procfs

- name: Allow i2c in boot config
  lineinfile:
    path: /boot/config.txt
    line: "{{item}}"
    state: present
  become: true
  with_items:
    - dtparam=i2c_arm=on

- name: Setup i2c, ipv6, and wifi kernel modules to load on startup
  lineinfile:
    path: /etc/modules
    line: "{{item}}"
    state: present
  become: true
  with_items:
    - i2c-dev
    - ipv6
    - 8192cu

