---
# Sets gateway as default route for clients

- name: "Generate wireguard keys"
  shell: "cd {{ansible_env.HOME}}; wg genkey | tee privatekey | wg pubkey > publickey"

- name: "Grab pubkey to send to gateway"
  shell: "cd {{ansible_env.HOME}}; echo $(cat publickey)"
  register: pubkey

- name: "Grab priv for our own config"
  shell: "cd {{ansible_env.HOME}}; echo $(cat privatekey)"
  register: privkey

- name: "Create wireguard interface file"
  file:
    path: "{{ansible_env.HOME}}/wg.conf"
    state: touch

- name: "Create wireguard interface file on gateway"
  delegate_to: "{{groups.gateway[0]}}"
  file:
    path: "{{ansible_env.HOME}}/wg.conf"
    state: touch

- name: "Generate wireguard interface config"
  lineinfile:
    line: "{{item}}"
    path: "{{ansible_env.HOME}}/wg.conf"
    state: present
  with_items:
   - "[Interface]"
   - "ListenPort = {{wg_port}}"
   - "PrivateKey = {{privkey.stdout}}"

- name: "Add entry to gateway config"
  delegate_to: "{{groups.gateway[0]}}"
  lineinfile:
    line: "{{item}}"
    path: "{{ansible_env.HOME}}/wg.conf"
    state: present
  with_items:
    - "[Peer]"
    - "Endpoint = {{generated_ip.stdout}}:{{wg_port}}"
    - "PublicKey = {{pubkey.stdout}}"
    - "AllowedIPs = 0.0.0.0/0,::/0"
