---
# Ansible playbook for preparing an rpi to run babel + Althea demo on startup

- hosts: all
  remote_user: pi
  vars:
   - devel: true
  roles:
    - secure_ssh
    - cleanup
    - package_setup
    - build_babel
    - template_deploy

- hosts: client
  remote_user: pi
  roles:
    - setup_client

- hosts: gateway
  remote_user: pi
  roles:
    - restart
    - setup_gateway

- hosts: all
  remote_user: pi
  roles:
    - restart
    - validate
