---
# Ansible playbook for preparing an rpi to run babel + Althea demo on startup

- hosts: all
  remote_user: pi
  roles:
    # - secure_ssh
    - package_setup
    - build_babel
    - template_deploy

- hosts: client:gateway
  remote_user: pi
  roles:
    - traffic_gen

- hosts: all
  remote_user: pi
  roles:
    - restart
