---
# Ansible playbook for preparing an rpi to run babel + Althea demo on startup

- hosts: all
  remote_user: pi
  vars:
   - devel: true
  roles:
    # - secure_ssh
    - cleanup
    - package_setup
    - build_babel
    - template_deploy

- hosts: client:gateway
  remote_user: pi
  roles:
    - traffic_gen

- hosts: client
  remote_user: pi
  roles:
    - setup_client_wireguard

- hosts: gateway
  remote_user: pi
  roles:
    - restart
    - setup_gateway_wireguard

- hosts: all
  remote_user: pi
  roles:
    - restart
    - validate
