---
# Configures iptables for forwarding

- name: "Generate wireguard keys"
  shell: "cd {{ansible_env.HOME}}; wg genkey | tee privatekey | wg pubkey > publickey"
  register: pubkey

- name: "Grab pubkey to send to clients"
  shell: "cd {{ansible_env.HOME}}; echo $(cat publickey)"
  register: pubkey

- name: "Grab priv for our own config"
  shell: "cd {{ansible_env.HOME}}; echo $(cat privatekey)"
  register: privkey

- name: "Create wireguard interface file"
  file:
    path: "{{ansible_env.HOME}}/wg.conf"
    state: touch

- name: "Create wireguard interface file on clients"
  delegate_to: "{{item}}"
  file:
    path: "{{ansible_env.HOME}}/wg.conf"
    state: touch
  with_items: "{{groups['client']}}"

- name: "Generate wireguard interface config"
  shell: "cd {{ansible_env.HOME}}; echo \"{{item}}\" >> wg.conf"
  with_items:
   - "[Interface]"
   - "ListenPort = {{wg_port}}"
   - "PrivateKey = {{privkey.stdout}}"

- name: "Add entry to client configs"
  delegate_to: "{{item[1]}}"
  lineinfile:
    line: "{{item[0]}}"
    path: "{{ansible_env.HOME}}/wg.conf"
    state: present
  with_nested:
    - ["[Peer]", "Endpoint = {{gateway_ip}}:{{wg_port}}", "PublicKey = {{pubkey.stdout}}", "AllowedIPs = 0.0.0.0/0,::/0"]
    - "{{groups['client']}}"
