---
# A cleanup role that restores everything to a workable provisioning state

- name: Disable services
  service: "name={{item}} enabled=false state=stopped"
  become: true
  ignore_errors: true
  with_items:
    - althea-demo
    - babeld
    - traffic-generator
    - stat-server
    - leaderboard

- name: Reload systemd
  shell: systemctl daemon-reload
  become: true