---
# Builds and installs babeld

- name: Delete old repo
  file:
     path: "{{ansible_env.HOME}}/babeld"
     state: absent
  become: true

- name: Clone Althea branch of Babeld
  git:
    repo: https://github.com/althea-mesh/babeld
    dest: "{{ansible_env.HOME}}/babeld"

- name: Build Babeld
  shell: "cd {{ansible_env.HOME}}/babeld; make -j8"

- name: Install Babeld
  shell: "cd {{ansible_env.HOME}}/babeld; \
          sudo make install"
