---
# templates and enables traffic gen

- name: Generate key
  user:
    name: pi
    generate_ssh_key: yes
  become: true

- name: Grab local ssh key
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_key

- name: Copy key to gateway
  authorized_key: "user=pi key={{ssh_key.stdout}}"
  delegate_to: "{{item}}"
  with_items: "{{groups['gateway']}}"  

- name: Template traffic generator script
  template:
    src: traffic-generator.sh
    dest: "{{ansible_env.HOME}}/traffic-generator.sh"

- name: Template service file
  template:
    src: traffic-generator.service
    dest: /etc/systemd/system/
  become: true

- name: Enable the services to run at startup
  service: "name=traffic-generator enabled=true"
  become: true
