---
# templates and enables traffic gen

- name: Template traffic generator script
  template:
    src: traffic-generator.sh
    dest: "{{ansible_env.HOME}}/traffic-generator.sh"
  tags:
    - trafficgen

- name: Template service file
  template:
    src: traffic-generator.service
    dest: /etc/systemd/system/
  become: true

- name: Enable the services to run at startup
  service: "name=traffic-generator enabled=true"
  become: true
