---
# Demo interface

- name: Template service file
  template:
    src: althea-demo.service
    dest: /etc/systemd/system/
  become: true

- name: Copy user interface scripts
  template:
    src: "{{item}}.py"
    dest: "{{ansible_env.HOME}}/{{item}}.py"
  tags:
    - python
  with_items:
    - client-gateway
    - common
    - intermediary

- name: Enable the service to run at startup
  service: "name=althea-demo enabled=true"
  become: true
