---
# Templates core services, babel and the screen


- name: Template service files
  template:
    src: "{{item}}"
    dest: /etc/systemd/system/
  become: true
  with_items:
    - babeld.service
    - althea-demo.service

- name: Copy user interface script
  template:
    src: user-interface.py
    dest: "{{ansible_env.HOME}}/user-interface.py"
  tags:
      - python

- name: "Generate ip"
  shell: "echo 10.28.{{ 254 | random }}.{{ 254 | random }}"
  register: generated_ip

- name: "Generate V6 ip"
  shell: "echo fe80::2cee:2fff:{{ 9999 | random }}:{{ 9999 | random }}"
  register: generatedv6_ip

- name: Template startup script
  template:
    src: start-babel.sh
    dest: "{{ansible_env.HOME}}/start-babel.sh"

- name: Enable the services to run at startup
  service: "name={{item}} enabled=true"
  become: true
  with_items:
    - babeld
    - althea-demo
