---
# Reboot and wait for the pi to come back


- name: Rebooting ...
  shell: sleep 1 & sudo reboot now
  async: 1
  poll: 0
  ignore_errors: true
  tags:
      - python
      - trafficgen

- name: Wait for pi to boot
  become: false
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
    timeout: 180
  tags:
    - python
    - trafficgen
