---
# Configures iptables for forwarding

- name: "Generate wireguard keys"
  shell: "cd {{ansible_env.HOME}}; wg genkey | tee privatekey | wg pubkey > publickey"
  register: pubkey

- name: "Generate wireguard interface config"
  shell: "cd {{ansible_env.HOME}}; echo \"{{item}}\" >> wg.conf"
  with_items:
   - "[Interface]\n"
   - "ListenPort = {{wg_port}}\n"
   - "PrivateKey = $(cat privatekey)\n"

- name: "Add entry to client configs"
  delegate_to: "{{item[1]}}"
  shell: "cd {{ansible_env.HOME}}; echo \"{{item[0]}}\" >> wg.conf"
  with_nested:
    - ["[Peer]\n", "Endpoint = {{gateway_ip}}::{{wg_port}}\n", "PublicKey = {{pubkey.stdout}}\n", "AllowedIPs = fe80::/64,ff02::/16\n"]
    - "{{groups['client']}}"

- name: Setup NAT
  shell: "{{item}}"
  become: true
  with_items:
    - "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"
    - "iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
    - "iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT"

- name: Save iptables rules
  shell: "iptables-save > /etc/iptables/rules.v4"
  become: true
